language: java
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/110a7c0daf817ba48ccc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
jdk:
- oraclejdk7
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle/caches/
env:
  global:
  - secure: Ps7+oTi5FfjwJ7tQ8G51wk30ZHqB1P4ZNXsGisn+r/8IJRxPs6VNIF/dPSkWLERs1tBvMG2sRz9nxaIwxXJwHXOkoBL/SXZHzOYwKTlsNcu72B6czxepIb0OAGWKAv6aCk9vAJkRzGX2Ogy+Hnn8AuQlPAPOplRjZm1AXj6smGM=
  - secure: C/RoUcQGZ6wB1nHnLN7dGMCbpjOObaviuXFxv5ZtocKfALmOZg6gOye5/LyJwvLwMaKtI434dHFvY29FIO0ntclx48xPYCjg6GsmzJOwQcwlLqIV1HQMczFDiYlMFSUbHn9d+JbwXxdd13g98aHtEif73bI0SXevyiqv4n/XsVo=
  - secure: LfLmAImQdX2LksJNJvo5R2tX/VEmBSudVgkZBIUhcTObmxcNvBzue0QyLa6w107s9U5G6PxfPOv4BB3qZogC3FmsY/qQus2JV9/0eP/hGVNZER1FlAe5mgHgzaoa39qNLQYdyb0jAmIR0r0X0DcF6yR+IAgj4rbN/wzXLc1Cw+s=
  - secure: XYdDt7fPTpIX2qvBbin4VR3ndfQ00xyebokpw0eXYQ6yvbS2H3lhFqBKuVnN40MTJXNL8ZBIm/wVe67QdAP0uJNlq6YhOf35XY45TfLTSZ0zJd+nJZMDIi8P0zrKDxv6vxnceaZwTrJy8Q1JiUrG4VA4Hb/T4zqftzvad9RT7lc=
